get_weight_history:
  description: "Retrieve historical weight data for a specific cat"
  fields:
    cat_id:
      description: "The ID of the cat to get weight history for"
      required: true
      selector:
        text:
    days:
      description: "Number of days of history to retrieve (default: 30)"
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 365
          mode: box
    request_id:
      description: "Optional request ID for tracking responses"
      required: false
      selector:
        text:
